<?php
// module/Event/view/event/event/add.phtml:

$title = 'Add event';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-6">
        <h1><?php echo $this->escapeHtml('Event list'); ?></h1><?php
        $list->setAttribute('action', $this->url('event', array('action' => 'delete')));
        $list->prepare();
        $element = $list->get('list-checkbox');
        $options = $element->getValueOptions();

        echo $this->form()->openTag($list);
        foreach ($options as $key => $option):
            echo "<div class='checkbox'><label><input name='list-checkbox[]' value='$key' type='checkbox'>$option</label>
                    <a href='". $this->url('event', array('action'=>'edit', 'id' => $key)) . "'>Edit</a></div>";
        endforeach;
//        echo $this->formMultiCheckbox($list->get('list-checkbox'));

        echo $this->formSubmit($list->get('submit'));
        echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-md-6">
        <h1><?php echo $this->escapeHtml($title); ?></h1> <?php
        $form->setAttribute('action', $this->url('event', array('action' => 'add')));
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        echo $this->formHidden($form->get('date'));?>
        <div class="form-group<?php echo (isset($messages['name'])) ? ' has-error' : '';?>"><?php
            echo $this->formRow($form->get('name'));?>
        </div>
        <div class="form-group"><?php
            echo $this->formRow($form->get('user_id')); ?>
        </div>
        <div class="form-group<?php echo (isset($messages['from'])) ? ' has-error' : '';?>"><?php
            echo $this->formRow($form->get('from')); ?>
        </div>
        <div class="form-group<?php echo (isset($messages['to'])) ? ' has-error' : '';?>"><?php
            echo $this->formRow($form->get('to')); ?>
        </div> <?php
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag(); ?>
    </div>
</div>

