<?php
// module/Event/view/event/event/add.phtml:

$title = 'Add new event';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('event', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('from'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();