<?php
// module/Event/view/event/event/delete.phtml:

$title = 'Delete events';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete</p>
    <ul><?php
    $ids = array();

    foreach ($this->events as $event):
        echo "<li>" . $this->escapeHtml($this->event_helper($event)) . "</li>";
        $ids[] = $event->id;
    endforeach; ?>
    </ul>
<?php
$url = $this->url('event', array(
    'action' => 'delete'
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div class="form-group"> <?php
        foreach ($ids as $id):
            echo "<input type='hidden' name='list-checkbox[]' value='$id' />";
        endforeach; ?>
        <input type="submit" class="btn btn-default" name="del" value="Yes" />
        <input type="submit" class="btn btn-default" name="del" value="No" />
    </div>
</form>