<?php
// module/Event/view/event/event/index.phtml:

$this->headTitle($this->date_helper(time()));
?>
<div class="row">
    <!-- <p><a href="<?php echo $this->url('event', array('action'=>'add'));?>">Add new event</a></p>--><?php
    foreach ($result as $date => $events) : ?>
        <h2><?php echo $this->escapeHtml($this->date_helper(strtotime($date))); ?></h2>
        <table class="table table-striped"><?php
            foreach ($events as $event) : ?>
                <tr>
                    <td><?php echo $this->escapeHtml(date('H:i', strtotime($event['from'])));?></td>
                    <td>@</td>
                    <td><?php echo $this->escapeHtml(date('H:i', strtotime($event['to'])));?></td>
                    <td><?php echo $this->escapeHtml($event['name']) . ", Booked by {$this->user_helper($event)}";?></td>
                </tr> <?php
            endforeach;?>
        </table><?php
    endforeach; ?>
</div>
