<?php
// module/Event/view/event/event/index.phtml:

$title = 'Today, ' . date('F jS Y', time());
$this->headTitle($title);
?>
<div class="row">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>
        <a href="<?php echo $this->url('event', array('action'=>'add'));?>">Add new event</a>
    </p>

    <table class="table table-striped">
        <?php foreach ($events as $event) : ?>
            <tr>
                <td><?php echo $this->escapeHtml(date('H:i',strtotime($event->from)));?></td>
                <td>@</td>
                <td><?php echo $this->escapeHtml(date('H:i',strtotime($event->to)));?></td>
                <td>
                    <?php echo $this->escapeHtml($event->name) . ", Booked by {$this->user_helper($event)}";?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
